name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Download Snake Action
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: AswinKumar1
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Retry if download fails
        if: ${{ failure() }}
        run: sleep 30

      - name: Set outputs
        run: |
          echo "GIF_PATH=${{ steps.snake-gif.outputs.gif_out_path }}" >> $GITHUB_ENV
          echo "SVG_PATH=${{ steps.snake-gif.outputs.svg_out_path }}" >> $GITHUB_ENV

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
